import { PUSubject, CircularNotification, StudyMaterial } from './types';

export const PU_SUBJECTS: PUSubject[] = [
  // Science
  { code: 'PHY', name: 'Physics', stream: 'Science' },
  { code: 'CHE', name: 'Chemistry', stream: 'Science' },
  { code: 'MAT', name: 'Mathematics', stream: 'Science' },
  { code: 'BIO', name: 'Biology', stream: 'Science' },
  { code: 'CS', name: 'Computer Science', stream: 'Science' },
  { code: 'ELE', name: 'Electronics', stream: 'Science' },
  
  // Commerce
  { code: 'ACC', name: 'Accountancy', stream: 'Commerce' },
  { code: 'BST', name: 'Business Studies', stream: 'Commerce' },
  { code: 'ECO', name: 'Economics', stream: 'Commerce' },
  { code: 'STAT', name: 'Statistics', stream: 'Commerce' },
  { code: 'CA', name: 'Computer Applications', stream: 'Commerce' },

  // Arts
  { code: 'HIS', name: 'History', stream: 'Arts' },
  { code: 'POL', name: 'Political Science', stream: 'Arts' },
  { code: 'SOC', name: 'Sociology', stream: 'Arts' },
  { code: 'GEO', name: 'Geography', stream: 'Arts' },

  // Languages / General
  { code: 'ENG', name: 'English', stream: 'General' },
  { code: 'KAN', name: 'Kannada', stream: 'General' },
  { code: 'HIN', name: 'Hindi', stream: 'General' },
  { code: 'SANS', name: 'Sanskrit', stream: 'General' },
];

export const INITIAL_CIRCULARS: CircularNotification[] = [
  {
    id: 'circ-1',
    title: 'Release of Class 12 / 2nd PU Model Question Papers for Board Exams',
    description: 'The Department of Pre-University Education (DPUE) has officially uploaded the model question papers with updated blueprint structures for the upcoming board exams. Students are advised to download the blueprints and plan their revisions accordingly.',
    postedDate: '2026-06-20',
    isOfficial: true,
    authority: 'Department of PU Education (DPUE)',
    category: 'Exams',
    important: true,
  },
  {
    id: 'circ-2',
    title: 'Practical Examination Guidelines & Directives',
    description: 'Guidelines and manual directions for conducting the 1st PU & 2nd PU Practical Examinations. Contains mark allocation schema, laboratory attendance registry criteria, and internal examiner selection workflows.',
    postedDate: '2026-06-15',
    isOfficial: true,
    authority: 'DPUE Board Office',
    category: 'Practicals',
    important: true,
  },
  {
    id: 'circ-3',
    title: 'Registration Card Correction Notice for PU Colleges',
    description: 'Pre-University Colleges have been granted a final window to perform spelling corrections, language selections, and stream modifications on Student Registration Certificates via the SATS portal.',
    postedDate: '2026-06-08',
    isOfficial: true,
    authority: 'DPUE SATS Portal',
    category: 'Administration',
    important: false,
  },
  {
    id: 'circ-4',
    title: 'Annual Academic Calendar & Holiday Declarations',
    description: 'Official academic timetable outlines the term schedules, mid-term break, and preparatory examination slots for Science, Commerce, and Arts cohorts for the current academic session.',
    postedDate: '2026-06-01',
    isOfficial: true,
    authority: 'Pre-University Board',
    category: 'Academic',
    important: false,
  }
];

export const INITIAL_MATERIALS: StudyMaterial[] = [
  {
    id: 'mat-1',
    title: '2nd PU Mathematics — Complete Integration Formula Cheat Sheet',
    description: 'A comprehensive 2-page formula list covering all integration rules, definite integrals properties, and standard substitutions. Perfect for rapid revision before the board exams!',
    subject: 'Mathematics',
    className: '2nd PU',
    stream: 'Science',
    category: 'Syllabus & Blueprint',
    modulePartition: 'Whole Syllabus',
    uploader: 'Prof. Sridhar Murthy',
    uploaderEmail: 'sridhar.murthy@pes.edu',
    uploadDate: '2026-06-22',
    fileSize: '845 KB',
    fileType: 'pdf',
    fileName: '2nd_PU_Maths_Integration_Formulas.pdf',
    downloadUrl: '/api/download/mat-1',
    likes: 48,
    downloads: 142,
    isCustom: false
  },
  {
    id: 'mat-2',
    title: '2nd PU Chemistry — Organic Conversions & Name Reactions Guide',
    description: 'A fully solved conversion guide mapping all aliphatic and aromatic name reactions from Aldehydes, Ketones, Amines, and Haloalkanes. Includes detailed step-by-step mechanism annotations.',
    subject: 'Chemistry',
    className: '2nd PU',
    stream: 'Science',
    category: 'Notes',
    modulePartition: 'Whole Syllabus',
    uploader: 'Deepa R.',
    uploaderEmail: 'deepa.chem@rvcollege.edu',
    uploadDate: '2026-06-20',
    fileSize: '1.4 MB',
    fileType: 'pdf',
    fileName: '2nd_PU_Chemistry_Organic_Conversions.pdf',
    downloadUrl: '/api/download/mat-2',
    likes: 87,
    downloads: 210,
    isCustom: false
  },
  {
    id: 'mat-3',
    title: '2nd PU Physics — Board Model Question Paper (Fully Solved)',
    description: 'Official model question paper solved with detailed step-by-step derivations for 5-mark electrostatic and current electricity questions. Verified according to latest PU board marking schemes.',
    subject: 'Physics',
    className: '2nd PU',
    stream: 'Science',
    category: 'Question Paper',
    modulePartition: 'Whole Syllabus',
    uploader: 'Prof. Ramesh Bhat',
    uploaderEmail: 'ramesh.physics@college.edu',
    uploadDate: '2026-06-18',
    fileSize: '2.1 MB',
    fileType: 'pdf',
    fileName: '2nd_PU_Physics_Solved_Model_Paper.pdf',
    downloadUrl: '/api/download/mat-3',
    likes: 125,
    downloads: 350,
    isCustom: false
  },
  {
    id: 'mat-4',
    title: '2nd PU Business Studies — Chapter-wise Case Studies Solver',
    description: 'Solved case study questions from past board examinations focusing on Principles of Management, Planning, and Marketing. Includes standard scoring keywords highlighted for students.',
    subject: 'Business Studies',
    className: '2nd PU',
    stream: 'Commerce',
    category: 'Notes',
    modulePartition: 'Whole Syllabus',
    uploader: 'Saraswathi Hegde',
    uploaderEmail: 'saraswathi.h@comcollege.in',
    uploadDate: '2026-06-19',
    fileSize: '1.1 MB',
    fileType: 'pdf',
    fileName: '2nd_PU_Business_Studies_Solved_Cases.pdf',
    downloadUrl: '/api/download/mat-4',
    likes: 36,
    downloads: 94,
    isCustom: false
  },
  {
    id: 'mat-5',
    title: "1st PU English — 'The Gentlemen of the Jungle' Analytical Summary",
    description: "An intensive literary summary and thematic analysis of Jomo Kenyatta's 'The Gentlemen of the Jungle'. Explores major themes of colonialism, power struggle, and fable elements with model 6-mark answers.",
    subject: 'English',
    className: '1st PU',
    stream: 'General',
    category: 'Notes',
    modulePartition: 'Whole Syllabus',
    uploader: 'Latha M.',
    uploaderEmail: 'latha.english@puedu.org',
    uploadDate: '2026-06-15',
    fileSize: '420 KB',
    fileType: 'pdf',
    fileName: '1st_PU_English_The_Gentlemen_of_the_Jungle.pdf',
    downloadUrl: '/api/download/mat-5',
    likes: 29,
    downloads: 118,
    isCustom: false
  }
];
